# Generated by Django 5.2.8 on 2025-11-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
    ]
