# Generated by Django 5.2.8 on 2025-11-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
    ]
