# Generated by Django 5.2.8 on 2025-11-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='history_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
