# Generated by Django 5.2.8 on 2025-11-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variant_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shop',
        ),
    ]
