# Generated by Django 5.2.8 on 2025-11-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_company_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='currency_type',
            field=models.CharField(default='uzs', max_length=10),
        ),
        migrations.AddField(
            model_name='variant',
            name='income_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='variant',
            name='outcome_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
