# Generated by Django 5.2.8 on 2025-11-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variant_currency_type_variant_income_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='imei_status',
            field=models.CharField(blank=True, choices=[('ALL', 'all'), ('ONE', 'one'), ('ONE WITH ESIM', 'one with esim')], null=True),
        ),
        migrations.CreateModel(
            name='Imei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('imei_code', models.CharField(max_length=20, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='products.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
