# Generated by Django 5.2.8 on 2025-11-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variant_imei_status_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imei',
            name='variant',
        ),
        migrations.AddField(
            model_name='imei',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.imei'),
        ),
    ]
