# Generated by Django 5.2.8 on 2025-12-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_imei_variant_imei_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='imei',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='products.variant'),
        ),
    ]
