# Generated by Django 5.2.8 on 2025-12-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_imei_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='currency_type',
        ),
    ]
