# Generated by Django 5.2.8 on 2025-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_variant_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imei',
            name='is_activated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activated'),
        ),
    ]
