# Generated by Django 5.2.8 on 2025-12-04 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_imei_is_activated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imei',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='imei',
            name='imei_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Imei Code'),
        ),
        migrations.AlterField(
            model_name='imei',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='products.variant', verbose_name='Variant'),
        ),
    ]
