# Generated by Django 5.2.8 on 2025-12-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_variant_imei_status_store_variant_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='store',
        ),
    ]
