# Generated by Django 5.2.8 on 2025-12-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_store_created_by_remove_store_shop_and_more'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider', verbose_name='Provider'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
