# Generated by Django 5.2.8 on 2025-12-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variant_provider_delete_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='provider',
        ),
    ]
