# Generated by Django 5.2.8 on 2025-12-07 19:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_variant_provider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='imei',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='variant',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
