# Generated by Django 5.2.8 on 2025-12-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_company_managers_alter_imei_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='history_status',
        ),
    ]
