# Generated by Django 5.2.8 on 2025-12-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_variant_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='income_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='outcome_price',
        ),
    ]
