# Generated by Django 5.2.8 on 2025-12-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_variant_income_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imei',
        ),
    ]
