# Generated by Django 5.2.8 on 2025-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_created_by_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceitem',
            name='income_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanceitem',
            name='outcome_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='income_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='outcome_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
