# Generated by Django 5.2.8 on 2025-12-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_balanceitem_income_price_and_more'),
        ('providers', '0002_alter_provider_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider', verbose_name='Provider'),
        ),
    ]
