# Generated by Django 5.2.8 on 2025-12-07 19:50

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_balanceitem_provider_documentitem_provider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='balanceitem',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documentitem',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='balanceitem',
            name='history_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='history_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
