# Generated by Django 5.2.8 on 2025-12-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_balanceitem_managers_alter_document_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceitem',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='qty',
        ),
    ]
