# Generated by Django 5.2.8 on 2025-12-09 21:36

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_balanceitem_qty_remove_documentitem_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_activated', models.BooleanField(blank=True, null=True, verbose_name='Activated')),
                ('imei_code', models.CharField(max_length=20, unique=True, verbose_name='Imei Code')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.imei')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='balanceitem',
            name='imeis',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='documents.imei'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='imeis',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='documents.imei'),
        ),
    ]
