# Generated by Django 5.2.8 on 2025-12-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_imei_balanceitem_imeis_documentitem_imeis'),
        ('providers', '0003_alter_provider_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider', verbose_name='Provider'),
        ),
    ]
