# Generated by Django 5.2.8 on 2025-12-09 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_balanceitem_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceitem',
            name='document_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documentitem', verbose_name='Document Item'),
        ),
    ]
