# Generated by Django 5.2.8 on 2025-12-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_balanceitem_document_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='documents.document'),
        ),
    ]
