# Generated by Django 5.2.8 on 2025-12-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_balanceitem_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='documents.document'),
        ),
    ]
