# Generated by Django 5.2.8 on 2025-11-24 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this shop (in addition to the creator).', related_name='managed_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
