# Generated by Django 5.2.8 on 2025-12-07 19:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_admins_shop_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shop',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
