# Generated by Django 5.2.8 on 2025-12-31 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this shop.', null=True, related_name='member_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this shop (in addition to the creator).', null=True, related_name='managed_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
