# Generated by Django 5.2.8 on 2025-12-31 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_members_alter_shop_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this shop (in addition to the creator).', related_name='managed_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this shop.', related_name='member_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
