# Generated by Django 5.2.8 on 2025-12-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('shops', '0002_shop_admins_shop_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='shops.shop', verbose_name='Provider'),
        ),
    ]
