# Generated by Django 5.2.8 on 2025-12-07 19:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_shop'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='provider',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
